name: 'Photography By '
favicon: null
layout_spectrum: 0.7182195109780878
typography_spectrum: 0.9914456454571337
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7800698943901807
  lightness: 0.30943131633102894
  saturation: 0.20758668635971844
  rhythmicContrast: 0.20597729622386396
purpose: []
